$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$ 
$ $Id$
$ 
$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
$ 
$ Licensed to the Apache Software  Foundation (ASF) under one or more
$ contributor  license agreements.  See  the NOTICE  file distributed
$ with  this  work  for  additional information  regarding  copyright
$ ownership.   The ASF  licenses this  file to  you under  the Apache
$ License, Version  2.0 (the  License); you may  not use  this file
$ except in  compliance with the License.   You may obtain  a copy of
$ the License at
$ 
$ http://www.apache.org/licenses/LICENSE-2.0
$ 
$ Unless required by applicable law or agreed to in writing, software
$ distributed under the  License is distributed on an  "AS IS" BASIS,
$ WITHOUT  WARRANTIES OR CONDITIONS  OF ANY  KIND, either  express or
$ implied.   See  the License  for  the  specific language  governing
$ permissions and limitations under the License.
$ 
$ Copyright 1994-2007 Rogue Wave Software, Inc.
$ 
$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

$set 1 Apache C++ Standard Library Error Messages
1 %s: %s: exception
2 %s: %s: unexpected exception
3 %s: %s: out of memory
4 %s: %s: bad cast
5 %s: %s: logic error
6 %s: %s: domain error
7 %s: %s: invalid argument
8 %s: %s: length error: size %u out of range [0, %u)
9 %s: %s: argument value %u out of range [0, %u)
10 %s: %s: runtime error
11 %s: %s: range error: invalid range [%d, %d)
12 %s: %s: overflow error
13 %s: %s: underflow error
14 %s: stream object has set ios::failbit
15 %s: stream object has set ios::badbit
16 %s: stream object has set ios::eofbit
17 %s: stream object has set %s
18 %s: %s: facet %u not present in locale (\"%s\")
19 %s: %s: bad locale name: \"%s\"
20 %s: %s: failed to construct locale name
21 %s: %s: conversion failed
22 %s: %s: invalid pointer %p
23 %s: %s: transformation failed
24 %s: %s: bad category value: %#x
